<?php

/*

Squad XML Generator by Tier1 Operations (http://tier1ops.eu) v0.2

This work is licenced under the Creative Commons by-nc-sa 3.0 Licence
https://creativecommons.org/licenses/by-nc-sa/3.0/deed.en

*/


	$database = " "; // That's the name of the database your phpBB is using.
	$dbserver = "localhost"; // Most likley localhost, but can be sth else.
	$dbuser   = " "; // Username of the user that has rights on the database.
	$dbpass   = " "; // Password of the user above.
	$db_prefix = "phpbb"; // Prefix for your phpBB installation. By default it's "phpbb".
	$squad_tag = "Tag"; // The short name of your group. E.g.: Tier1, ST, 6th, 7=CAV, KH, or else.
	$squad_name_full = "Name"; // Well obviously that's your group's full name.
	$squad_web = "http://yourdomain.tld"; // URL of your website.
	$squad_contact_mail = "email@yourdomain.tld"; // 
	$squad_info = " "; // A motto or else. We don't use it, because it's displayed in Arma under your squad logo.
	
?>
